Задача выполнена
ivannikitin-com/lustshop pull request #77
Opened 2020-04-25 07:27 UTC by gruzdevas

https://github.com/ivannikitin-com/lustshop/issues/68

2020-04-27 04:08 UTC, stug111 requested changes

2020-04-27 04:08 UTC, stug111 commented on src/sass/style.scss
> +.faq {
Эти стили нужно вынести в отдельный файл

2020-04-27 04:08 UTC, stug111 commented on typography.php
> +</div>
Верстку блока вынеси в отдельный файл

2020-04-27 08:54 UTC, gruzdevas commented on typography.php
> +</div>
Верстка перенесена.

2020-04-29 04:24 UTC, stug111 approved these changes

2020-04-29 04:25 UTC, merged