Стилизовать страницу "Корзина" #80
ivannikitin-com/lustshop pull request #88
Opened 2020-05-09 13:42 UTC by gruzdevas

https://github.com/ivannikitin-com/lustshop/issues/80

2020-05-12 04:38 UTC, stug111 requested changes

2020-05-12 04:38 UTC, stug111 commented on src/sass/blocks/button/frontend.scss
> +    // background-color: green;
зауомментированный код не оставляем

2020-05-12 04:38 UTC, stug111 commented on src/sass/elements/form.scss
> +  opacity: 0.5 !important;
тут точно без  `important` никак?

2020-05-12 04:38 UTC, stug111 commented on src/sass/layout/woocommerce/cart.scss
> +        // @extend .form-control--circle;
```suggestion

```

2020-05-12 04:38 UTC, stug111 commented on src/sass/layout/woocommerce/cart.scss
> +}
Давай стилизацию уведомлений вынесем в отдельный файл, так как они появляются не тольк она странице корзины

2020-05-12 04:38 UTC, stug111 commented on src/sass/layout/woocommerce/cart.scss
> +}
я так понимаю это тоже к уведомлению относится

2020-05-12 04:38 UTC, stug111 commented on src/sass/layout/woocommerce/cart.scss
> +}
это обобщенный стиль и он будет работать на всем сайте глобально
может повлечь за собой перебивку стилей, тут надо либо обратиться через класс либо внутри класса `.woocommerce-cart`

2020-05-12 04:38 UTC, stug111 commented on src/sass/layout/woocommerce/cart.scss
> +}
и тут тоже

2020-05-12 04:38 UTC, stug111 commented on src/sass/layout/woocommerce/cart.scss
> +}
это уведомление?

2020-05-12 04:38 UTC, stug111 commented on src/sass/layout/woocommerce/cart.scss
> +.woocommerce-shipping-methods {
судя по названию класса, то это относится уже к старнице оформления заказа, если этот так, для страницы оформления заказа есть отдельная задача и должно быть в отдельном файле

2020-05-12 04:38 UTC, stug111 commented on src/sass/style.scss
> +.screen-reader-text {
что показывает элемент с этим классом? и должно ли это находиться в в этом файле?

2020-05-12 04:38 UTC, stug111 commented on wc.css
> +}
что это за файл? и почему он в css формате?

2020-05-12 17:59 UTC, gruzdevas commented on src/sass/elements/form.scss
> +  opacity: 0.5 !important;
Думаю, что можно и без.

2020-05-12 18:01 UTC, gruzdevas commented on src/sass/layout/woocommerce/cart.scss
> +}
Да.

2020-05-12 18:02 UTC, gruzdevas commented on src/sass/layout/woocommerce/cart.scss
> +}
Точно не знаю. Я взяла все эти правила из storefront.

2020-05-12 18:03 UTC, gruzdevas commented on src/sass/layout/woocommerce/cart.scss
> +.woocommerce-shipping-methods {
Методы доставки есть и в Корзине.

2020-05-12 18:03 UTC, gruzdevas commented on src/sass/style.scss
> +.screen-reader-text {
Его надо перенести в общие правила.

2020-05-12 18:04 UTC, gruzdevas commented on wc.css
> +}
Ой. Это мой. Я сначала хотела сделать, как ты сказал - стили скопировать, а потом переносить к себе. Удаляй.

2020-05-13 10:26 UTC, gruzdevas commented on src/sass/blocks/button/frontend.scss
> +    // background-color: green;
Сделано.

2020-05-13 10:29 UTC, gruzdevas commented on src/sass/elements/form.scss
> +  opacity: 0.5 !important;
Сделано.

2020-05-13 10:30 UTC, gruzdevas commented on src/sass/layout/woocommerce/cart.scss
> +        // @extend .form-control--circle;
Сделано.

2020-05-13 10:34 UTC, gruzdevas commented on src/sass/layout/woocommerce/cart.scss
> +}
Сделано.

2020-05-13 10:35 UTC, gruzdevas commented on wc.css
> +}
Удалила.

2020-05-13 10:36 UTC, gruzdevas commented on src/sass/layout/woocommerce/cart.scss
> +.woocommerce-shipping-methods {
Вадим, что тут делать?

2020-05-13 10:46 UTC, gruzdevas commented on src/sass/layout/woocommerce/cart.scss
> +.woocommerce-shipping-methods {
Сделано.

2020-05-14 02:41 UTC, stug111 requested changes

2020-05-14 02:41 UTC, stug111 commented on src/sass/elements/form.scss
> +  & button.disabled,
почему ты тут обращаешься через  body?

2020-05-14 02:41 UTC, stug111 commented on src/sass/blocks/messages/style.scss
> +}
это нужно было создать не в папке blocks а в elements и файл назвать `woo-messages` чтобы было понятно к чему относится

2020-05-14 02:41 UTC, stug111 commented on src/sass/blocks/messages/style.scss
> +  color: $white;
вот это так и не исправила, ты этим стилей сделаешь все ссылке на сайте белыми, надо обращаться по селектору

2020-05-14 02:47 UTC, stug111 commented on src/sass/style.scss
> +.screen-reader-text {
Не увидел чтобы перенесла этот стиль, он вообще пропал

2020-05-14 07:08 UTC, gruzdevas commented on src/sass/elements/form.scss
> +  & button.disabled,
А как еще? Чтобы не писать !impoprtant.

2020-05-14 07:17 UTC, gruzdevas commented on src/sass/blocks/messages/style.scss
> +}
Сделано.

2020-05-14 07:47 UTC, gruzdevas commented on src/sass/blocks/messages/style.scss
> +  color: $white;
Исправила.

2020-05-14 09:01 UTC, stug111 approved these changes

2020-05-14 09:09 UTC, merged