Стилизовать виджет "Блог" #85
ivannikitin-com/lustshop pull request #93
Opened 2020-05-17 13:21 UTC by gruzdevas

https://github.com/ivannikitin-com/lustshop/issues/85
Работа заняла 0,5 ч.

2020-05-18 03:52 UTC, stug111 requested changes

2020-05-18 03:52 UTC, stug111 commented on src/sass/layout/widgets/post-widget.scss
> +    @extend .wp-block-lustshop-button;
Надо ховер для таких кнопо сделать
будет инвертация цветов

2020-05-18 03:52 UTC, stug111 commented on src/sass/layout/widgets/post-widget.scss
> +  .attachment-lustshop-widget-post {
давай не будем так писать, а будем все таки по возможности использовать БЭМ

тебе надо в файле `wp-content/themes/lustshop/template-parts/components/widgets/post-widget.php` на 11-ой строчке написать вот так
```<?php echo get_the_post_thumbnail($id, 'lustshop-widget-post', array('class' => 'post-widget__image')); ?>```

и использовать для стилей `post-widget__image`

2020-05-18 03:55 UTC, stug111 commented
Еще надо настроить отступы между виджетами
![image](https://user-images.githubusercontent.com/27495069/82172971-0581f080-98f6-11ea-8674-d852ae2b0b22.png)

2020-06-02 15:12 UTC, gruzdevas commented on src/sass/layout/widgets/post-widget.scss
> +    @extend .wp-block-lustshop-button;
Сделано.

2020-06-02 15:17 UTC, gruzdevas commented on src/sass/layout/widgets/post-widget.scss
> +  .attachment-lustshop-widget-post {
Сделано.

2020-06-02 15:27 UTC, gruzdevas commented
Отступы добавлены.

2020-06-03 03:30 UTC, stug111 requested changes

2020-06-03 03:30 UTC, stug111 commented on src/sass/layout/widgets/post-widget.scss
>      &:hover {
почему мы делаем какой-то кастомный ховер для этой кнопки? по идеи все ховеры должны быть описаны в классе `.wp-block-lustshop-button`

2020-06-03 03:30 UTC, stug111 commented on src/sass/layout/widgets/widgets.scss
> +    }
лучше тогда вот так

```suggestion
    &:not(:last-child) {
      margin-bottom: 2.6rem;
    }
```
а на 50-ой строке убрать

2020-06-03 03:30 UTC, stug111 commented on src/sass/layout/widgets/post-widget.scss
> +
это все лучше прописать у самой svg

2020-06-03 06:43 UTC, gruzdevas commented on src/sass/layout/widgets/post-widget.scss
> +
Не срабатывает. Там fill прописан внутри.

2020-06-03 06:59 UTC, stug111 commented on src/sass/layout/widgets/post-widget.scss
> +
верно, тебе надо в svg(в верстке имеется ввиду) значение fill переписать на `currentColor `

2020-06-03 09:31 UTC, gruzdevas commented on src/sass/layout/widgets/post-widget.scss
> +
Сделано.

2020-06-03 09:35 UTC, gruzdevas commented on src/sass/layout/widgets/widgets.scss
> +    }
Сделано.

2020-06-03 09:43 UTC, gruzdevas commented on src/sass/layout/widgets/post-widget.scss
>      &:hover {
Сделано.

2020-06-03 13:08 UTC, stug111 requested changes

2020-06-03 13:08 UTC, stug111 commented on src/sass/blocks/button/frontend.scss
> +  }
```suggestion
  .icon {
    margin-left: 9px;
  }
```

2020-06-03 13:08 UTC, stug111 commented on inc/widgets/post-widget.php
> +                echo "<a class='post-widget__button-more' href='". get_category_link($category_id) ."'>" . __('Open blog', 'lustshop') . "<svg xmlns='http://www.w3.org/2000/svg' width='7' height='12'
```suggestion
                echo "<a class='post-widget__button-more' href='". get_category_link($category_id) ."'>" . __('Open blog', 'lustshop') . "<svg class="icon" xmlns='http://www.w3.org/2000/svg' width='7' height='12'><path data-name='-e-arrow-pink' d='M6.992 6a.986.986 0 0 1-.292.7l-4.989 5a.991.991 0 0 1-1.413.01 1.007 1.007 0 0 1 0-1.42L4.581 6 .298 1.7A1 1 0 0 1 1.712.29l4.989 5a1.009 1.009 0 0 1 .291.71z' fill='currentColor' fill-rule='evenodd'/></svg></a>";
```

2020-06-04 07:01 UTC, stug111 requested changes

2020-06-04 07:01 UTC, stug111 commented on src/sass/blocks/button/frontend.scss
> +  // }
```suggestion

```

2020-06-04 07:02 UTC, stug111 commented
Света, пожалуйста повнимательней делай правки

2020-06-05 09:41 UTC, stug111 approved these changes

2020-06-05 09:44 UTC, merged