Стилизовать страницу "Оформление заказа" #81
ivannikitin-com/lustshop pull request #94
Opened 2020-05-18 17:28 UTC by gruzdevas

https://github.com/ivannikitin-com/lustshop/issues/81

2020-05-20 04:39 UTC, stug111 requested changes

2020-05-20 04:39 UTC, stug111 commented on src/sass/elements/form.scss
> +    user-select: none;
не нужно писать префиксы, автопрефиксер сделает все сам

2020-05-20 04:39 UTC, stug111 commented on src/sass/elements/form.scss
> +  padding-top: 8px !important;
что мешает использовать эти стили без important?

2020-05-20 04:39 UTC, stug111 commented on src/sass/layout/woocommerce/checkout.scss
> +    position: static;
не совсем понимаю для чего это нужно

2020-05-20 04:39 UTC, stug111 commented on src/sass/layout/woocommerce/checkout.scss
> +  /* stylelint-disable selector-max-id */
это отключение правила уже не нужно

2020-05-20 04:39 UTC, stug111 commented on src/sass/layout/woocommerce/checkout.scss
> +      padding-left: 0;
правильно понимаю что тут нестандартная сетка используется и поэтому ты перебиваешь bootstrap?

2020-05-25 13:07 UTC, gruzdevas commented on src/sass/elements/form.scss
> +    user-select: none;
Сделано.

2020-05-25 13:12 UTC, gruzdevas commented on src/sass/elements/form.scss
> +  padding-top: 8px !important;
Вот это перебивает:
```

  .input-text {
    @extend .form-control;
  }
```

2020-05-25 13:17 UTC, gruzdevas commented on src/sass/layout/woocommerce/checkout.scss
> +    position: static;
Это я перенесла из storefront. Можно и убрать. Я тоже не поняла зачем, но решила перенести.

2020-05-25 13:18 UTC, gruzdevas commented on src/sass/layout/woocommerce/checkout.scss
> +  /* stylelint-disable selector-max-id */
Убрала.

2020-05-25 13:18 UTC, gruzdevas commented on src/sass/layout/woocommerce/checkout.scss
> +      padding-left: 0;
Да. Здесь те же классы, что и у bootstrap.

2020-05-25 13:21 UTC, stug111 commented on src/sass/elements/form.scss
> +  padding-top: 8px !important;
попробуй обратиться не к тегу, а через класс должно работать

2020-05-25 13:21 UTC, stug111 commented on src/sass/layout/woocommerce/checkout.scss
> +    position: static;
давай тогда уберем

2020-05-25 13:48 UTC, gruzdevas commented on src/sass/layout/woocommerce/checkout.scss
> +    position: static;
Убрала.

2020-05-25 13:54 UTC, gruzdevas commented on src/sass/elements/form.scss
> +  padding-top: 8px !important;
Сделано.

2020-05-25 14:43 UTC, stug111 approved these changes
Осталось решить конфликты

2020-05-28 02:44 UTC, merged